spring:
  profiles:
    active: local
  application:
    name: gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: hello
          uri: lb://hello
          predicates:
            - Path=/hello/**
        - id: greet
          uri: lb://greet
          predicates:
            - Path=/greet/**




